"""Change the tile column in title.

Revision ID: 119f43a08026
Revises: e4a27812756e
Create Date: 2022-05-17 09:40:48.418522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119f43a08026'
down_revision = 'e4a27812756e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_column('posts', 'tile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tile', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
